USE [DB_BIBLIOTECA]
GO
/****** Object:  StoredProcedure [dbo].[BLI_INSERT_LIVRO]    Script Date: 08/27/2015 23:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BLI_INSERT_LIVRO]
(
	@NOME  	  AS VARCHAR(80),
	@AUTOR	  AS VARCHAR(80)
) 

AS 
	INSERT INTO TB_LIVROS (NOME, AUTOR)
	VALUES (@NOME, @AUTOR) 